export const countries = [
  { id: 1, locale: 'AF', value: 'Afghanistan' },
  { id: 2, locale: 'AL', value: 'Albania' },
  { id: 3, locale: 'DZ', value: 'Algeria' },
  { id: 4, locale: 'AS', value: 'American Samoa' },
  { id: 5, locale: 'AD', value: 'Andorra' },
  { id: 6, locale: 'AO', value: 'Angola' },
  { id: 7, locale: 'AI', value: 'Anguilla' },
  { id: 8, locale: 'AQ', value: 'Antarctica' },
  { id: 9, locale: 'AG', value: 'Antigua and Barbuda' },
  { id: 10, locale: 'AR', value: 'Argentina' },
  { id: 11, locale: 'AM', value: 'Armenia' },
  { id: 12, locale: 'AW', value: 'Aruba' },
  { id: 13, locale: 'AU', value: 'Australia' },
  { id: 14, locale: 'AT', value: 'Austria' },
  { id: 15, locale: 'AZ', value: 'Azerbaijan' },
  { id: 16, locale: 'BS', value: 'Bahamas (the)' },
  { id: 17, locale: 'BH', value: 'Bahrain' },
  { id: 18, locale: 'BD', value: 'Bangladesh' },
  { id: 19, locale: 'BB', value: 'Barbados' },
  { id: 20, locale: 'BY', value: 'Belarus' },
  { id: 21, locale: 'BE', value: 'Belgium' },
  { id: 22, locale: 'BZ', value: 'Belize' },
  { id: 23, locale: 'BJ', value: 'Benin' },
  { id: 24, locale: 'BM', value: 'Bermuda' },
  { id: 25, locale: 'BT', value: 'Bhutan' },
  { id: 26, locale: 'BO', value: 'Bolivia' },
  { id: 27, locale: 'BQ', value: 'Bonaire, Sint Eustatius and Saba' },
  { id: 28, locale: 'BA', value: 'Bosnia and Herzegovina' },
  { id: 29, locale: 'BW', value: 'Botswana' },
  { id: 30, locale: 'BV', value: 'Bouvet Island' },
  { id: 31, locale: 'BR', value: 'Brazil' },
  { id: 32, locale: 'IO', value: 'British Indian Ocean Territory' },
  { id: 33, locale: 'BN', value: 'Brunei Darussalam' },
  { id: 34, locale: 'BG', value: 'Bulgaria' },
  { id: 35, locale: 'BF', value: 'Burkina Faso' },
  { id: 36, locale: 'BI', value: 'Burundi' },
  { id: 37, locale: 'CV', value: 'Cabo Verde' },
  { id: 38, locale: 'KH', value: 'Cambodia' },
  { id: 39, locale: 'CM', value: 'Cameroon' },
  { id: 40, locale: 'CA', value: 'Canada' },
  { id: 41, locale: 'KY', value: 'Cayman Islands' },
  { id: 42, locale: 'CF', value: 'Central African Republic' },
  { id: 43, locale: 'TD', value: 'Chad' },
  { id: 44, locale: 'CL', value: 'Chile' },
  { id: 45, locale: 'CN', value: 'China' },
  { id: 46, locale: 'CX', value: 'Christmas Island' },
  { id: 47, locale: 'CC', value: 'Cocos (Keeling) Islands' },
  { id: 48, locale: 'CO', value: 'Colombia' },
  { id: 49, locale: 'KM', value: 'Comoros' },
  { id: 50, locale: 'CG', value: 'Congo' },
  { id: 51, locale: 'CD', value: 'Congo (the Democratic Republic of the)' },
  { id: 52, locale: 'CK', value: 'Cook Islands' },
  { id: 53, locale: 'CR', value: 'Costa Rica' },
  { id: 54, locale: 'HR', value: 'Croatia' },
  { id: 55, locale: 'CU', value: 'Cuba' },
  { id: 56, locale: 'CW', value: 'Curaçao' },
  { id: 57, locale: 'CY', value: 'Cyprus' },
  { id: 58, locale: 'CZ', value: 'Czechia' },
  { id: 59, locale: 'CI', value: "Côte d'Ivoire" },
  { id: 60, locale: 'DK', value: 'Denmark' },
  { id: 61, locale: 'DJ', value: 'Djibouti' },
  { id: 62, locale: 'DM', value: 'Dominica' },
  { id: 63, locale: 'DO', value: 'Dominican Republic' },
  { id: 64, locale: 'EC', value: 'Ecuador' },
  { id: 65, locale: 'EG', value: 'Egypt' },
  { id: 66, locale: 'SV', value: 'El Salvador' },
  { id: 67, locale: 'GQ', value: 'Equatorial Guinea' },
  { id: 68, locale: 'ER', value: 'Eritrea' },
  { id: 69, locale: 'EE', value: 'Estonia' },
  { id: 70, locale: 'SZ', value: 'Eswatini' },
  { id: 71, locale: 'ET', value: 'Ethiopia' },
  { id: 72, locale: 'FK', value: 'Falkland Islands (Malvinas)' },
  { id: 73, locale: 'FO', value: 'Faroe Islands' },
  { id: 74, locale: 'FJ', value: 'Fiji' },
  { id: 75, locale: 'FI', value: 'Finland' },
  { id: 76, locale: 'FR', value: 'France' },
  { id: 77, locale: 'GF', value: 'French Guiana' },
  { id: 78, locale: 'PF', value: 'French Polynesia' },
  { id: 79, locale: 'TF', value: 'French Southern Territories' },
  { id: 80, locale: 'GA', value: 'Gabon' },
  { id: 81, locale: 'GM', value: 'Gambia' },
  { id: 82, locale: 'GE', value: 'Georgia' },
  { id: 83, locale: 'DE', value: 'Germany' },
  { id: 84, locale: 'GH', value: 'Ghana' },
  { id: 85, locale: 'GI', value: 'Gibraltar' },
  { id: 86, locale: 'GR', value: 'Greece' },
  { id: 87, locale: 'GL', value: 'Greenland' },
  { id: 88, locale: 'GD', value: 'Grenada' },
  { id: 89, locale: 'GP', value: 'Guadeloupe' },
  { id: 90, locale: 'GU', value: 'Guam' },
  { id: 91, locale: 'GT', value: 'Guatemala' },
  { id: 92, locale: 'GG', value: 'Guernsey' },
  { id: 93, locale: 'GN', value: 'Guinea' },
  { id: 94, locale: 'GW', value: 'Guinea-Bissau' },
  { id: 95, locale: 'GY', value: 'Guyana' },
  { id: 96, locale: 'HT', value: 'Haiti' },
  { id: 97, locale: 'HM', value: 'Heard Island and McDonald Islands' },
  { id: 98, locale: 'VA', value: 'Holy See' },
  { id: 99, locale: 'HN', value: 'Honduras' },
  { id: 100, locale: 'HK', value: 'Hong Kong' },
  { id: 101, locale: 'HU', value: 'Hungary' },
  { id: 102, locale: 'IS', value: 'Iceland' },
  { id: 103, locale: 'IN', value: 'India' },
  { id: 104, locale: 'ID', value: 'Indonesia' },
  { id: 105, locale: 'IR', value: 'Iran' },
  { id: 106, locale: 'IQ', value: 'Iraq' },
  { id: 107, locale: 'IE', value: 'Ireland' },
  { id: 108, locale: 'IM', value: 'Isle of Man' },
  { id: 109, locale: 'IL', value: 'Israel' },
  { id: 110, locale: 'IT', value: 'Italy' },
  { id: 111, locale: 'JM', value: 'Jamaica' },
  { id: 112, locale: 'JP', value: 'Japan' },
  { id: 113, locale: 'JE', value: 'Jersey' },
  { id: 114, locale: 'JO', value: 'Jordan' },
  { id: 115, locale: 'KZ', value: 'Kazakhstan' },
  { id: 116, locale: 'KE', value: 'Kenya' },
  { id: 117, locale: 'KI', value: 'Kiribati' },
  { id: 118, locale: 'KP', value: 'North Korea' },
  { id: 119, locale: 'KR', value: 'South Korea' },
  { id: 120, locale: 'KW', value: 'Kuwait' },
  { id: 121, locale: 'KG', value: 'Kyrgyzstan' },
  { id: 122, locale: 'LA', value: 'Laos' },
  { id: 123, locale: 'LV', value: 'Latvia' },
  { id: 124, locale: 'LB', value: 'Lebanon' },
  { id: 125, locale: 'LS', value: 'Lesotho' },
  { id: 126, locale: 'LR', value: 'Liberia' },
  { id: 127, locale: 'LY', value: 'Libya' },
  { id: 128, locale: 'LI', value: 'Liechtenstein' },
  { id: 129, locale: 'LT', value: 'Lithuania' },
  { id: 130, locale: 'LU', value: 'Luxembourg' },
  { id: 131, locale: 'MO', value: 'Macao' },
  { id: 132, locale: 'MG', value: 'Madagascar' },
  { id: 133, locale: 'MW', value: 'Malawi' },
  { id: 134, locale: 'MY', value: 'Malaysia' },
  { id: 135, locale: 'MV', value: 'Maldives' },
  { id: 136, locale: 'ML', value: 'Mali' },
  { id: 137, locale: 'MT', value: 'Malta' },
  { id: 138, locale: 'MH', value: 'Marshall Islands' },
  { id: 139, locale: 'MQ', value: 'Martinique' },
  { id: 140, locale: 'MR', value: 'Mauritania' },
  { id: 141, locale: 'MU', value: 'Mauritius' },
  { id: 142, locale: 'YT', value: 'Mayotte' },
  { id: 143, locale: 'MX', value: 'Mexico' },
  { id: 144, locale: 'FM', value: 'Micronesia' },
  { id: 145, locale: 'MD', value: 'Moldova' },
  { id: 146, locale: 'MC', value: 'Monaco' },
  { id: 147, locale: 'MN', value: 'Mongolia' },
  { id: 148, locale: 'ME', value: 'Montenegro' },
  { id: 149, locale: 'MS', value: 'Montserrat' },
  { id: 150, locale: 'MA', value: 'Morocco' },
  { id: 151, locale: 'MZ', value: 'Mozambique' },
  { id: 152, locale: 'MM', value: 'Myanmar' },
  { id: 153, locale: 'NA', value: 'Namibia' },
  { id: 154, locale: 'NR', value: 'Nauru' },
  { id: 155, locale: 'NP', value: 'Nepal' },
  { id: 156, locale: 'NL', value: 'Netherlands' },
  { id: 157, locale: 'NC', value: 'New Caledonia' },
  { id: 158, locale: 'NZ', value: 'New Zealand' },
  { id: 159, locale: 'NI', value: 'Nicaragua' },
  { id: 160, locale: 'NE', value: 'Niger' },
  { id: 161, locale: 'NG', value: 'Nigeria' },
  { id: 162, locale: 'NU', value: 'Niue' },
  { id: 163, locale: 'NF', value: 'Norfolk Island' },
  { id: 164, locale: 'MK', value: 'North Macedonia' },
  { id: 165, locale: 'MP', value: 'Northern Mariana Islands' },
  { id: 166, locale: 'NO', value: 'Norway' },
  { id: 167, locale: 'OM', value: 'Oman' },
  { id: 168, locale: 'PK', value: 'Pakistan' },
  { id: 169, locale: 'PW', value: 'Palau' },
  { id: 170, locale: 'PS', value: 'Palestine, State of' },
  { id: 171, locale: 'PA', value: 'Panama' },
  { id: 172, locale: 'PG', value: 'Papua New Guinea' },
  { id: 173, locale: 'PY', value: 'Paraguay' },
  { id: 174, locale: 'PE', value: 'Peru' },
  { id: 175, locale: 'PH', value: 'Philippines' },
  { id: 176, locale: 'PN', value: 'Pitcairn' },
  { id: 177, locale: 'PL', value: 'Poland' },
  { id: 178, locale: 'PT', value: 'Portugal' },
  { id: 179, locale: 'PR', value: 'Puerto Rico' },
  { id: 180, locale: 'QA', value: 'Qatar' },
  { id: 181, locale: 'RE', value: 'Réunion' },
  { id: 182, locale: 'RO', value: 'Romania' },
  { id: 183, locale: 'RU', value: 'Russian Federation' },
  { id: 184, locale: 'RW', value: 'Rwanda' },
  { id: 185, locale: 'BL', value: 'Saint Barthélemy' },
  {
    id: 186,
    locale: 'SH',
    value: 'Saint Helena, Ascension and Tristan da Cunha',
  },
  { id: 187, locale: 'KN', value: 'Saint Kitts and Nevis' },
  { id: 188, locale: 'LC', value: 'Saint Lucia' },
  { id: 189, locale: 'MF', value: 'Saint Martin (French part)' },
  { id: 190, locale: 'PM', value: 'Saint Pierre and Miquelon' },
  { id: 191, locale: 'VC', value: 'Saint Vincent and the Grenadines' },
  { id: 192, locale: 'WS', value: 'Samoa' },
  { id: 193, locale: 'SM', value: 'San Marino' },
  { id: 194, locale: 'ST', value: 'Sao Tome and Principe' },
  { id: 195, locale: 'SA', value: 'Saudi Arabia' },
  { id: 196, locale: 'SN', value: 'Senegal' },
  { id: 197, locale: 'RS', value: 'Serbia' },
  { id: 198, locale: 'SC', value: 'Seychelles' },
  { id: 199, locale: 'SL', value: 'Sierra Leone' },
  { id: 200, locale: 'SG', value: 'Singapore' },
  { id: 201, locale: 'SX', value: 'Sint Maarten (Dutch part)' },
  { id: 202, locale: 'SK', value: 'Slovakia' },
  { id: 203, locale: 'SI', value: 'Slovenia' },
  { id: 204, locale: 'SB', value: 'Solomon Islands' },
  { id: 205, locale: 'SO', value: 'Somalia' },
  { id: 206, locale: 'ZA', value: 'South Africa' },
  {
    id: 207,
    locale: 'GS',
    value: 'South Georgia and the South Sandwich Islands',
  },
  { id: 208, locale: 'SS', value: 'South Sudan' },
  { id: 209, locale: 'ES', value: 'Spain' },
  { id: 210, locale: 'LK', value: 'Sri Lanka' },
  { id: 211, locale: 'SD', value: 'Sudan' },
  { id: 212, locale: 'SR', value: 'Suriname' },
  { id: 213, locale: 'SJ', value: 'Svalbard and Jan Mayen' },
  { id: 214, locale: 'SE', value: 'Sweden' },
  { id: 215, locale: 'CH', value: 'Switzerland' },
  { id: 216, locale: 'SY', value: 'Syrian Arab Republic' },
  { id: 217, locale: 'TW', value: 'Taiwan' },
  { id: 218, locale: 'TJ', value: 'Tajikistan' },
  { id: 219, locale: 'TZ', value: 'Tanzania' },
  { id: 220, locale: 'TH', value: 'Thailand' },
  { id: 221, locale: 'TL', value: 'Timor-Leste' },
  { id: 222, locale: 'TG', value: 'Togo' },
  { id: 223, locale: 'TK', value: 'Tokelau' },
  { id: 224, locale: 'TO', value: 'Tonga' },
  { id: 225, locale: 'TT', value: 'Trinidad and Tobago' },
  { id: 226, locale: 'TN', value: 'Tunisia' },
  { id: 227, locale: 'TR', value: 'Turkey' },
  { id: 228, locale: 'TM', value: 'Turkmenistan' },
  { id: 229, locale: 'TC', value: 'Turks and Caicos Islands' },
  { id: 230, locale: 'TV', value: 'Tuvalu' },
  { id: 231, locale: 'UG', value: 'Uganda' },
  { id: 232, locale: 'UA', value: 'Ukraine' },
  { id: 233, locale: 'AE', value: 'United Arab Emirates' },
  { id: 234, locale: 'GB', value: 'United Kingdom' },
  { id: 235, locale: 'US', value: 'United States' },
  { id: 236, locale: 'UM', value: 'United States Minor Outlying Islands' },
  { id: 237, locale: 'UY', value: 'Uruguay' },
  { id: 238, locale: 'UZ', value: 'Uzbekistan' },
  { id: 239, locale: 'VU', value: 'Vanuatu' },
  { id: 240, locale: 'VE', value: 'Venezuela' },
  { id: 241, locale: 'VN', value: 'Viet Nam' },
  { id: 242, locale: 'VG', value: 'Virgin Islands (British)' },
  { id: 243, locale: 'VI', value: 'Virgin Islands (U.S.)' },
  { id: 244, locale: 'WF', value: 'Wallis and Futuna' },
  { id: 245, locale: 'EH', value: 'Western Sahara' },
  { id: 246, locale: 'YE', value: 'Yemen' },
  { id: 247, locale: 'ZM', value: 'Zambia' },
  { id: 248, locale: 'ZW', value: 'Zimbabwe' },
];
